version: "3.1"

services:
  gomsgsender:
    build: './'
    stdin_open: true
    tty: true
    environment:
      GO_ID: docker-compose-go
    networks:
      - kafka


networks:
  kafka:
    external:
      name: dockerized-kafka_kafka # see https://github.com/anoop-git/dockerized-kafka